import { ANIMATIONS_TYPES, SHAPE_TYPES } from "../../../utils/constants";
import { animation, Shape } from "../../../utils/schemas";

export default {
  keyframes: [
    { time: 0, duration: 10, animationId: "SHAPE_1_INIT" },
    // { time: 0, duration: 10, animationId: "SHAPE_TEXT_INIT" },
    // { time: 3000, duration: 1000, animationId: "_1_SHAPE1_MOVE_X" },
    // { time: 3000, duration: 1000, animationId: "_9_SHAPE1_SCALE_X" },
    // { time: 3000, duration: 1000, animationId: "_10_SHAPE1_SCALE_Y" },
    // { time: 3000, duration: 1000, animationId: "_5_SHAPE_TEXT_MOVE_X" },
    // { time: 3000, duration: 1000, animationId: "_7_SHAPE_TEXT_FADE_IN" },
    // { time: 4000, duration: 1000, animationId: "_2_SHAPE1_MOVE_Y" },
    // { time: 4500, duration: 1000, animationId: "_6_SHAPE_TEXT_MOVE_X" },
    // { time: 5000, duration: 1000, animationId: "_8_SHAPE_TEXT_FADE_OUT" },
    // { time: 5000, duration: 1000, animationId: "_3_SHAPE1_MOVE_X" },
    // { time: 6000, duration: 1000, animationId: "_4_SHAPE1_MOVE_Y" },
    // { time: 6500, duration: 1000, animationId: "_11_SHAPE1_SCALE_Y" },
    // { time: 6500, duration: 1000, animationId: "_12_SHAPE1_SCALE_X" },
  ],
  animations: {
    SHAPE_1_INIT: animation({
      type: ANIMATIONS_TYPES.moveX,
      value: 100,
      prevValue: 100,
      duration: 1000,
      shapeId: "SHAPE1",
    }),
    // _1_SHAPE1_MOVE_X: animation({
    //   type: ANIMATIONS_TYPES.moveX,
    //   value: 200,
    //   prevValue: 100,
    //   duration: 1000,
    //   shapeId: "SHAPE1",
    // }),
    // _2_SHAPE1_MOVE_Y: animation({
    //   type: ANIMATIONS_TYPES.moveY,
    //   value: 200,
    //   prevValue: 100,
    //   duration: 1000,
    //   shapeId: "SHAPE1",
    // }),
    // _3_SHAPE1_MOVE_X: animation({
    //   type: ANIMATIONS_TYPES.moveX,
    //   value: 100,
    //   prevValue: 200,
    //   duration: 1000,
    //   shapeId: "SHAPE1",
    // }),
    // _4_SHAPE1_MOVE_Y: animation({
    //   type: ANIMATIONS_TYPES.moveY,
    //   value: 100,
    //   prevValue: 200,
    //   duration: 1000,
    //   shapeId: "SHAPE1",
    // }),
    // _9_SHAPE1_SCALE_X: animation({
    //   type: ANIMATIONS_TYPES.scaleX,
    //   duration: 1000,
    //   prevValue:30,
    //   value:200,
    //   shapeId: "SHAPE1",
    // }),
    // _10_SHAPE1_SCALE_Y: animation({
    //   type: ANIMATIONS_TYPES.scaleY,
    //   duration: 1000,
    //   prevValue:30,
    //   value:200,
    //   shapeId: "SHAPE1",
    // }),
    // _11_SHAPE1_SCALE_Y: animation({
    //   type: ANIMATIONS_TYPES.scaleY,
    //   duration: 1000,
    //   prevValue:200,
    //   value:30,
    //   shapeId: "SHAPE1",
    // }),
    // _12_SHAPE1_SCALE_X: animation({
    //   type: ANIMATIONS_TYPES.scaleX,
    //   duration: 1000,
    //   prevValue:200,
    //   value:30,
    //   shapeId: "SHAPE1",
    // }),
    // _5_SHAPE_TEXT_MOVE_X: animation({
    //   type: ANIMATIONS_TYPES.moveX,
    //   value: 700,
    //   prevValue: 300,
    //   duration: 1000,
    //   shapeId: "SHAPE_TEXT",
    // }),
    // _6_SHAPE_TEXT_MOVE_X: animation({
    //   type: ANIMATIONS_TYPES.moveX,
    //   value: 500,
    //   prevValue: 700,
    //   duration: 1000,
    //   shapeId: "SHAPE_TEXT",
    // }),
    // _7_SHAPE_TEXT_FADE_IN: animation({
    //   type: ANIMATIONS_TYPES.fadeIn,
    //   duration: 1000,
    //   prevValue:0,
    //   value:1,
    //   shapeId: "SHAPE_TEXT",
    // }),
    // _8_SHAPE_TEXT_FADE_OUT: animation({
    //   type: ANIMATIONS_TYPES.fadeOut,
    //   duration: 1000,
    //   prevValue:1,
    //   value:0,
    //   shapeId: "SHAPE_TEXT",
    // })
  },
  currentTimeStamp: 0,
  requestAnimationFrameLastTimeStamp: 0,
  previousRequestAnimationFrameEndDate: 0,
  previousRequestAnimationID: undefined,
  timelineLength: 6500 + 1000, // the last timestamp's time + the last timestamp's duration
  shapes: [
    Shape({
      x: 100,
      y: 100,
      height: 30,
      width: 30,
      id: "SHAPE_1",
      type: SHAPE_TYPES.BOX,
    }),
    // Shape({
    //   x: 300,
    //   y: 300,
    //   height: 50,
    //   width: 50,
    //   id: "SHAPE_TEXT",
    //   opacity:0,
    //   type: SHAPE_TYPES.TEXT,
    //   content: "SOUFIAN ZAMEL",
    // }),
  ],
};
